version: '3.8'

services:
  jupyter:
    build: stupytar
    container_name: jupyter_notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./Data:/home/jovyan/Data
    environment:
      - JUPYTER_ENABLE_LAB=yes
    restart: always
